CC = gcc
CFLAGS = -Wall -g

# Archivos fuente
SRC = src/main.c src/wificollector_collect.c src/wificollector_display src/wificollector_display_all src/wificollector_quit

OBJ = $(SRC:.c=.o)

TARGET = programa

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)