main: main.o wificollector_collect.o wificollector_display.o wificollector_display_all.o wificollector_quit.o wificollector_delete_net.o
main.o:
	gcc -c ../src/main.c
wificollector_collect.o:
	gcc -c ../src/wificollector_collect.c
wificollector_display.o:
	gcc -c ../src/wificollector_display.c
wificollector_display_all.o:
	gcc -c ../src/wificollector_display_all.c
wificollector_quit.o:
	gcc -c ../src/wificollector_quit.c
wificollector_delete_net.o:
	gcc -c ../src/wificollector_quit.c
clean:
	rm main \
	*.o